### ISSUE TITLE
ask for intron_UTR_db.txt

### ISSUE THREAD

**Issue by Sunshaoe** [GEmilioHO/IGFinder#1]
The downloaded (http://www.nextgenbioinformatics.org/IntronDB/download.php) was not available for intron_UTR_db.txt.

**Comment by GEmilioHO** [comment]
Hi @Sunshaoe,

It seems that the webpage is not working any more. You can download the data set from [here](https://drive.google.com/file/d/1c1t4eMQZ4SSHD0-iUiHph8eivTDYUq0l/view?usp=share_link).

I would suggest to filter the file keeping only your species of interest (as it is a big file and otherwise would take very long to run).
